### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = 'F:/Paper/Test/comprint-main/models/Comprint_Siamese_Full_jpg_ps_full', errno = 13, error message = 'Permission denied', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by Admgan** [IDLabMedia/comprint#5]
After I set the path, I clicked Run and found this error. The Comprint_Siamese_Full_jpg_ps_full folder contains keras_metadata.pb, saved_model.pb and variables folders. Are there any files missing? thank you for your patience.

F:\Anaconda3\envs\mytensorflow\python.exe F:/Paper/Test/comprint-main/test.py
Using TensorFlow backend.
2024-02-27 17:15:19.883081: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "F:/Paper/Test/comprint-main/test.py", line 7, in <module>
    ks.models.load_model(str1)
  File "F:\Anaconda3\envs\mytensorflow\lib\site-packages\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "F:\Anaconda3\envs\mytensorflow\lib\site-packages\keras\engine\saving.py", line 583, in load_model
    with H5Dict(filepath, mode='r') as h5dict:
  File "F:\Anaconda3\envs\mytensorflow\lib\site-packages\keras\utils\io_utils.py", line 191, in __init__
    self.data = h5py.File(path, mode=mode)
  File "F:\Anaconda3\envs\mytensorflow\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "F:\Anaconda3\envs\mytensorflow\lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'F:/Paper/Test/comprint-main/models/Comprint_Siamese_Full_jpg_ps_full', errno = 13, error message = 'Permission denied', flags = 0, o_flags = 0)
![Wrong](https://github.com/IDLabMedia/comprint/assets/35370383/43368bc0-475c-4e5f-9837-1a66dac3da51)

**Comment by hmareen** [comment]
Hi Admgan.

There are no files missing. It appears that you have a Permission Denied Error. Do you have reading rights on that folder and those files?

Kind regards,
Hannes
